title: Rafie Darmawan
logo: priv-repo/assets/img/foto profil.jpeg
description: An adaptable individual capable of working independently or within a team, love to gain new knowledge everyday. [Click here to download my latest CV] (https://docs.google.com/document/d/1abkt_lp35excaujVkxwchwL6lfRbtucd/edit?usp=drive_link&ouid=101061277946539398819&rtpof=true&sd=true)
# show_downloads: true
theme: jekyll-theme-minimal
