title: Rafie Darmawan
logo: /assets/img/foto profil.jpeg
description: An adaptable individual capable of working independently or within a team, love to gain new knowledge everyday. Former was-to-be (AB-Initio) Commercial Pilot who switched career in 2021.
# show_downloads: true
theme: jekyll-theme-minimal
